In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
house = pd.read_excel('cr2.xlsx', sheet_name='house',header=None)

In [3]:
tube = pd.read_excel('cr2.xlsx', sheet_name='tube',header=None)

In [4]:
tube.columns = ['lat', 'long','name']

In [5]:
house.columns = ['price','lat', 'long']

In [6]:
latMAX = 51.7
latMIN = 51.3
longMAX = 0.3
longMIN = -0.6

In [7]:
r= house.shape[0]
location = []


for i in range(r):
    lat = house['lat'][i]
    long = house['long'][i]
    if lat>=latMIN and lat<=latMAX and long>=longMIN and long<=longMAX:
        location.append([lat,long,house['price'][i]])
        #price.append(house['price'][i])

In [8]:
rr = tube.shape[0]
location_tube = []
name = []

for i in range(rr):
    lat = house['lat'][i]
    long = house['long'][i]
    if lat>=latMIN and lat<=latMAX and long>=longMIN and long<=longMAX:
        location_tube.append([lat,long])
        name.append(tube['name'][i])

In [9]:
location=np.array(location)
#price=np.array(price)
location_tube=np.array(location_tube)
name=np.array(name)

In [156]:
from random import seed
from random import randrange

# Split a dataset into k folds
def cross_validation_split(dataset, folds=3):
    dataset_split = []
    dataset_copy = dataset
    fold_size = int(len(dataset) / folds)
    for i in range(folds):
        fold =[]
        while len(fold) < fold_size:
            index = randrange(len(dataset_copy))
            fold.append(dataset_copy[index,:])
            dataset_copy=np.delete(dataset_copy, index,0)
        dataset_split.append(fold)
    return dataset_split

In [158]:
folds = cross_validation_split(location)

In [10]:
from mpl_toolkits import mplot3d
%matplotlib notebook

In [ ]:
fig = plt.figure()
ax = plt.axes(projection='3d')
ax.scatter3D(location_tube[:,0], location_tube[:,1],color='g')
ax.set_xlabel('lat')
ax.set_ylabel('long')

In [ ]:
fig = plt.figure()
ax = plt.axes(projection='3d')
ax.scatter3D(location[:,0], location[:,1],location[:,2],c='r')

ax.scatter3D(location_tube[:,0], location_tube[:,1],color='g')
ax.set_xlabel('lat')
ax.set_ylabel('long')

In [16]:
muMin = np.min(london)
muMax = np.max(london)
NumBasisFnsx = 7
NumBasisFnsy = 7
mu = np.zeros((NumBasisFnsx*NumBasisFnsy, 2))
s = (muMax - muMin)/(NumBasisFnsx)
for ii in range(NumBasisFnsx):
        for jj in range(NumBasisFnsy):
                mu[(ii)*NumBasisFnsx+jj, 0] = muMin[0] + (ii-1)*(muMax[0]-muMin[0])/(NumBasisFnsx-1)
                mu[(ii)*NumBasisFnsy+jj, 1] = muMin[1] + (jj-1)*(muMax[1]-muMin[1])/(NumBasisFnsy-1)

In [132]:
mu.shape

(49, 2)

In [18]:
s[0]

0.05549707142857179

In [129]:
from tqdm import tqdm

def basis_unigrid(data, mu):
    numBasisFncs = len(mu)+1
    Thetas = np.zeros((len(data), numBasisFncs))
    for ii in tqdm(range(len(data))):
        for jj in range(numBasisFncs):
            if jj == 0:
                Thetas[ii,jj] = 1
            else:
                Thetas[ii,jj] = np.exp( -( (((data['lat'][ii]-mu[jj-1,0])**2)/(2*(s[0]**2))) + \
                                       (((data['long'][ii]-mu[jj-1,1])**2)/(2*(s[1]**2))) ) )
    return Thetas

In [157]:
from random import seed
from random import randrange

# Split a dataset into k folds
def cross_validation_split(dataset, folds=3):
    dataset_split = []
    dataset_copy = dataset
    fold_size = int(len(dataset) / folds)
    for i in range(folds):
        fold =[]
        while len(fold) < fold_size:
            index = randrange(len(dataset_copy))
            fold.append(dataset_copy[index,:])
            dataset_copy=np.delete(dataset_copy, index,0)
        dataset_split.append(fold)
    return dataset_split

In [160]:
london

             lat      long   price
0      51.506954 -0.019372   563.0
1      51.527400 -0.189900  1473.0
2      51.512018 -0.199160  3250.0
3      51.526153 -0.253267  1105.0
4      51.564530 -0.305760   900.0
5      51.454484 -0.340631  1075.0
6      51.521841 -0.482566   800.0
7      51.434876 -0.133334   850.0
8      51.596043 -0.204212  1625.0
9      51.496423 -0.194583  2275.0
10     51.507514 -0.021136  2947.0
11     51.484064  0.078141   700.0
12     51.456562 -0.020283   800.0
13     51.405637 -0.093263   699.0
14     51.405637 -0.093263   699.0
15     51.399043 -0.082860   750.0
16     51.499974 -0.213864  1473.0
17     51.464863 -0.265296  1127.0
18     51.457212 -0.005853  1096.0
19     51.513304 -0.149788  1993.0
20     51.426799 -0.331342  1300.0
21     51.634296 -0.048104   750.0
22     51.618839 -0.055654   850.0
23     51.525135 -0.188377  1430.0
24     51.434303 -0.178715   953.0
25     51.443351 -0.146927  1300.0
26     51.538123 -0.207027  1170.0
27     51.538271 -0.211902  1647.0
28     51.629572 -0.125290   950.0
29     51.615271 -0.062190   550.0
...          ...       ...     ...
14526  51.542336 -0.163020  1842.0
14527  51.527125 -0.063767  1842.0
14528  51.546836 -0.220171  1430.0
14529  51.437838 -0.014025   725.0
14530  51.453266  0.014044   650.0
14531  51.434303 -0.178715  1096.0
14532  51.562880 -0.013606   910.0
14533  51.593095 -0.172343  1062.0
14534  51.417869 -0.203676  1000.0
14535  51.644679 -0.040188   800.0
14536  51.407741 -0.026243   800.0
14537  51.610057 -0.147128   953.0
14538  51.494280 -0.034962  1408.0
14539  51.494015 -0.149441  2167.0
14540  51.505988 -0.214009  1842.0
14541  51.462206 -0.132920  1647.0
14542  51.462206 -0.132920  1647.0
14543  51.462206 -0.132920  1647.0
14544  51.468813 -0.205396  1517.0
14545  51.462148 -0.140181  1603.0
14546  51.512489 -0.068441  1603.0
14547  51.511174 -0.098435  1712.0
14548  51.514947 -0.275315  1250.0
14549  51.518308 -0.193860  1517.0
14550  51.494413 -0.177454  1582.0
14551  51.496663 -0.179187  2817.0
14552  51.511737 -0.034524  1733.0
14553  51.519603 -0.121823  2058.0
14554  51.539809 -0.199431  1408.0
14555  51.503944 -0.241046  1517.0

[14556 rows x 3 columns]

In [164]:
london[['lat','long']].values

array([[ 5.15069539e+01, -1.93718000e-02],
       [ 5.15274000e+01, -1.89900000e-01],
       [ 5.15120178e+01, -1.99160200e-01],
       ...,
       [ 5.15196027e+01, -1.21822800e-01],
       [ 5.15398093e+01, -1.99431400e-01],
       [ 5.15039438e+01, -2.41045600e-01]])

In [188]:
from sklearn.model_selection import StratifiedKFold

kfold = StratifiedKFold(n_splits=5,random_state=1).split(london[['lat','long']].values, london['price'].values)

In [189]:
for k, (train, test) in enumerate(kfold):
    print(london.iloc[test])

/Users/yuekang/anaconda3/lib/python3.5/site-packages/sklearn/model_selection/_split.py:626: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)

             lat      long    price
0      51.506954 -0.019372    563.0
1      51.527400 -0.189900   1473.0
2      51.512018 -0.199160   3250.0
3      51.526153 -0.253267   1105.0
4      51.564530 -0.305760    900.0
5      51.454484 -0.340631   1075.0
6      51.521841 -0.482566    800.0
7      51.434876 -0.133334    850.0
8      51.596043 -0.204212   1625.0
9      51.496423 -0.194583   2275.0
10     51.507514 -0.021136   2947.0
11     51.484064  0.078141    700.0
12     51.456562 -0.020283    800.0
13     51.405637 -0.093263    699.0
15     51.399043 -0.082860    750.0
16     51.499974 -0.213864   1473.0
17     51.464863 -0.265296   1127.0
18     51.457212 -0.005853   1096.0
19     51.513304 -0.149788   1993.0
20     51.426799 -0.331342   1300.0
21     51.634296 -0.048104    750.0
22     51.618839 -0.055654    850.0
23     51.525135 -0.188377   1430.0
24     51.434303 -0.178715    953.0
25     51.443351 -0.146927   1300.0
26     51.538123 -0.207027   1170.0
27     51.538271 -0.211902   1647.0
28     51.629572 -0.125290    950.0
29     51.615271 -0.062190    550.0
30     51.607690 -0.118679    550.0
...          ...       ...      ...
12338  51.506060 -0.270495   1274.0
12339  51.508535 -0.281020    958.0
12361  51.462342 -0.167633   1270.0
12600  51.494363  0.072344    915.0
12650  51.527007 -0.194992   1515.0
12671  51.556531 -0.222610   1021.0
12857  51.538922 -0.147296   2405.0
12877  51.504379 -0.045810    120.0
12900  51.564035 -0.336268   1070.0
12945  51.493717 -0.184296   6249.0
12947  51.560218 -0.115058   1060.0
13038  51.496428 -0.208521   2036.0
13072  51.485448 -0.216986   1344.0
13120  51.457141 -0.080779    940.0
13351  51.548046 -0.199243   1084.0
13359  51.431433 -0.201174  12000.0
13393  51.475800 -0.045395    724.0
13501  51.555000 -0.141868   1699.0
13547  51.505842 -0.115049   3857.0
13607  51.408849 -0.040435    833.0
13644  51.378247 -0.061444   1042.0
13651  51.591999  0.029360   1099.0
13753  51.576859  0.030233    615.0
13884  51.424229  0.048578    299.0
13917  51.590781 -0.021250    799.0
14025  51.419241 -0.155545    530.0
14081  51.652566 -0.093757    435.0
14113  51.556264 -0.046209    640.0
14352  51.541915 -0.088855   1621.0
14488  51.626474 -0.114273    620.0

[3231 rows x 3 columns]
             lat      long   price
14     51.405637 -0.093263   699.0
482    51.540016 -0.151957  1650.0
543    51.491619 -0.195114  1755.0
661    51.511570 -0.180238  3163.0
736    51.463600 -0.234140  1195.0
786    51.492927 -0.195849  1079.0
829    51.505952 -0.005556  1599.0
886    51.520056 -0.161681  1711.0
964    51.527400 -0.189900  2123.0
1139   51.411443 -0.061118   765.0
1215   51.509748  0.029329   455.0
1301   51.597872 -0.109217  2000.0
1342   51.517623 -0.055755  2123.0
1383   51.461680 -0.176082  1195.0
1485   51.500905  0.071043   888.0
1497   51.507704 -0.134315  2232.0
1511   51.624341 -0.099122  2000.0
1545   51.572811 -0.100016   975.0
1561   51.552140 -0.185696  1755.0
1619   51.491814 -0.019404   888.0
1633   51.538239 -0.259330   975.0
1635   51.552140 -0.185696  1755.0
1637   51.517685 -0.258537   996.0
1764   51.534961  0.025701   390.0
1782   51.589831  0.027647   975.0
1851   51.510869 -0.154657  3445.0
1881   51.552140 -0.185696  1473.0
1924   51.531595 -0.182560  2123.0
1931   51.492050 -0.165203  2492.0
1961   51.469039 -0.067881   830.0
...          ...       ...     ...
12514  51.587110 -0.304502   660.0
12522  51.519105 -0.074540   702.0
12601  51.618701 -0.107711   560.0
12647  51.529430 -0.114426  1433.0
12755  51.521732 -0.266607   465.0
12933  51.528027 -0.462192   430.0
12946  51.513269 -0.098282  5126.0
12989  51.591496 -0.102971   945.0
13000  51.395050  0.009171   770.0
13001  51.608021 -0.008723   785.0
13036  51.623896 -0.086680   399.0
13219  51.412731 -0.225465  2500.0
13237  51.592814 -0.234095   598.0
13258  51.460437 -0.007827   610.0
13321  51.423521 -0.210943  3000.0
13430  51.459561 -0.322693  1551.0
13481  51.480913 -0.236867  1070.0
13491  51.618020 -0.185390   862.0
13564  51.484318 -0.084829  1144.0
13605  51.566126 -0.020907   470.0
13606  51.566126 -0.020907  1270.0
13613  51.598565 -0.353692   940.0
13656  51.502120 -0.186174  2903.0
13703  51.516557 -0.319455  2002.0
13928  51.492961 -0.112669  1256.0
14004  51.485514  0.115799   369.0
14042  51.449762 -0.003714   451.0
14347  51.435912 -0.145941  1274.0
14353  51.541915 -0.088855  1621.0
14487  51.614074 -0.106828   915.0

[2993 rows x 3 columns]
             lat      long   price
1122   51.534031 -0.122326  1711.0
1445   51.509654 -0.267921  1079.0
1636   51.552140 -0.185696  1755.0
2001   51.454839 -0.317606  1195.0
2292   51.511811 -0.073094  1599.0
2487   51.496025 -0.270301  1650.0
2538   51.467135 -0.116122  1755.0
2642   51.552140 -0.185696  1755.0
2790   51.496025 -0.270301  1650.0
2848   51.518180 -0.131231  2340.0
3244   51.494883 -0.129057  2297.0
3249   51.487146 -0.149756  2340.0
3407   51.530443  0.020734   776.0
3432   51.401537 -0.105677  2000.0
3548   51.489727 -0.156699  2080.0
3553   51.489727 -0.156699  2123.0
3802   51.501273 -0.018184  2080.0
3818   51.445113 -0.149841   715.0
3865   51.491799 -0.164291  2492.0
3884   51.492050 -0.165203  2492.0
3887   51.492050 -0.165203  2492.0
3896   51.492270 -0.165767  2492.0
3914   51.485766 -0.182882  2297.0
3972   51.515040 -0.072360  1426.0
4046   51.517459 -0.195826  2492.0
4050   51.503490 -0.018220  1841.0
4051   51.503490 -0.018220  1841.0
4064   51.524642 -0.084277  2037.0
4078   51.520264 -0.160554  2297.0
4082   51.492050 -0.165203  2492.0
...          ...       ...     ...
11420  51.549641 -0.259861   860.0
11445  51.607821 -0.420134   810.0
11565  51.489720 -0.189263  2253.0
11732  51.439973  0.009782   790.0
11847  51.407408 -0.051355   525.0
11867  51.373387  0.072098   871.0
11899  51.511570 -0.180238  2968.0
12000  51.511570 -0.180238  2968.0
12175  51.511570 -0.180238  2968.0
12248  51.515349 -0.172411  1946.0
12337  51.506060 -0.270495  1205.0
12406  51.497989 -0.049693   858.0
12476  51.511570 -0.180238  2968.0
12648  51.511570 -0.180238  2968.0
12664  51.515239 -0.325795   595.0
12668  51.511605 -0.180007  2968.0
12730  51.501669 -0.164957  7042.0
12951  51.467182 -0.107260   702.0
12987  51.531625 -0.193301  1085.0
13191  51.509189 -0.296970  1092.0
13363  51.612186 -0.436210  2500.0
13681  51.519622 -0.464705   475.0
13739  51.641602 -0.078205   862.0
13767  51.647351 -0.135320   546.0
14046  51.492065 -0.178357  1734.0
14055  51.383411 -0.127536   785.0
14186  51.461527 -0.047037   945.0
14193  51.505604 -0.148762  2773.0
14277  51.507227 -0.101087  2882.0
14367  51.522675 -0.262021  1185.0

[2857 rows x 3 columns]
             lat      long   price
3736   51.412622 -0.219225  1650.0
4203   51.501337 -0.098638  1711.0
4472   51.543113 -0.190966  1599.0
4723   51.526954 -0.178980  3358.0
4738   51.549911  0.052186   455.0
4814   51.513790 -0.186803  2297.0
4957   51.490744 -0.140362  1755.0
4970   51.487543 -0.221971  1240.0
4973   51.487543 -0.221971   980.0
5107   51.427630 -0.168350   996.0
5423   51.460957 -0.212526  1375.0
5785   51.524042 -0.051032   737.0
5846   51.513061 -0.197363  3358.0
5938   51.418481 -0.188989  1350.0
6021   51.552140 -0.185696  1755.0
6107   51.494024 -0.176713  1777.0
6113   51.492065 -0.178357  1777.0
6115   51.492065 -0.178357  1777.0
6117   51.492065 -0.178357  1777.0
6118   51.492065 -0.178357  1777.0
6192   51.497740 -0.163663  2752.0
6235   51.525286 -0.192680  1516.0
6426   51.482906 -0.047580   737.0
6659   51.496794  0.012936  1350.0
6729   51.509400 -0.001515  1350.0
6756   51.492647  0.069403  1075.0
6808   51.562759 -0.061691  1079.0
6841   51.527921 -0.095272  1777.0
6844   51.510430 -0.193320  1755.0
6861   51.529450 -0.096415  1777.0
...          ...       ...     ...
12988  51.548909  0.005209   725.0
13049  51.580097 -0.347757   675.0
13053  51.511570 -0.180238  2968.0
13061  51.511605 -0.180007  2968.0
13073  51.424953 -0.205674   895.0
13126  51.644679 -0.040188   725.0
13148  51.362729 -0.064208   725.0
13155  51.498736 -0.179550  7042.0
13213  51.523951 -0.140432  2448.0
13214  51.489096 -0.179952  1677.0
13368  51.568624 -0.015824   758.0
13423  51.523987 -0.085806  2448.0
13431  51.459757 -0.137753   920.0
13457  51.508349  0.129216   675.0
13462  51.486893 -0.135093  1972.0
13487  51.511605 -0.180007  2968.0
13492  51.596043 -0.204212   758.0
13560  51.511570 -0.180238  2968.0
13577  51.596981 -0.143920  1101.0
13593  51.519622 -0.464705   350.0
13594  51.511570 -0.180238  2968.0
13608  51.423958 -0.034495  2200.0
13624  51.511570 -0.180238  2968.0
13682  51.519622 -0.464705   475.0
13683  51.519622 -0.464705   475.0
13723  51.518717 -0.264222   702.0
13830  51.448162 -0.113153   854.0
14093  51.502255 -0.097542  1750.0
14119  51.671947 -0.014502   680.0
14416  51.487891 -0.150191  2427.0

[2773 rows x 3 columns]
             lat      long   price
7406   51.439266 -0.152438  1426.0
7701   51.506390 -0.004245  1599.0
7787   51.547596  0.003597  4550.0
8373   51.513646 -0.147823  4117.0
8417   51.497101 -0.159801  3358.0
8435   51.483293 -0.301370  1275.0
8490   51.515077 -0.316900  1275.0
8797   51.491814 -0.019404  4767.0
8870   51.386978 -0.082362   455.0
8952   51.517459 -0.195826  1755.0
8962   51.521764 -0.154931  2340.0
9015   51.490445 -0.276734  2000.0
9039   51.524940 -0.073553  8667.0
9057   51.438532 -0.187428  1348.0
9059   51.487891 -0.150191  2362.0
9139   51.369163 -0.117975  1600.0
9220   51.436547 -0.151491  1075.0
9222   51.515017 -0.266427  1075.0
9237   51.466434 -0.154245  1350.0
9288   51.417150 -0.197424  1350.0
9371   51.621000 -0.152862   585.0
9389   51.516057 -0.140161  3358.0
9396   51.520264 -0.160554  1711.0
9454   51.491437 -0.155818  5417.0
9461   51.531780 -0.105380  2318.0
9548   51.520600 -0.074670  2080.0
9698   51.522315 -0.144420  6500.0
9724   51.529768 -0.144482  3445.0
9771   51.522269 -0.144682  6500.0
9800   51.529768 -0.144482  3358.0
...          ...       ...     ...
14526  51.542336 -0.163020  1842.0
14527  51.527125 -0.063767  1842.0
14528  51.546836 -0.220171  1430.0
14529  51.437838 -0.014025   725.0
14530  51.453266  0.014044   650.0
14531  51.434303 -0.178715  1096.0
14532  51.562880 -0.013606   910.0
14533  51.593095 -0.172343  1062.0
14534  51.417869 -0.203676  1000.0
14535  51.644679 -0.040188   800.0
14536  51.407741 -0.026243   800.0
14537  51.610057 -0.147128   953.0
14538  51.494280 -0.034962  1408.0
14539  51.494015 -0.149441  2167.0
14540  51.505988 -0.214009  1842.0
14541  51.462206 -0.132920  1647.0
14542  51.462206 -0.132920  1647.0
14543  51.462206 -0.132920  1647.0
14544  51.468813 -0.205396  1517.0
14545  51.462148 -0.140181  1603.0
14546  51.512489 -0.068441  1603.0
14547  51.511174 -0.098435  1712.0
14548  51.514947 -0.275315  1250.0
14549  51.518308 -0.193860  1517.0
14550  51.494413 -0.177454  1582.0
14551  51.496663 -0.179187  2817.0
14552  51.511737 -0.034524  1733.0
14553  51.519603 -0.121823  2058.0
14554  51.539809 -0.199431  1408.0
14555  51.503944 -0.241046  1517.0

[2702 rows x 3 columns]

In [130]:
theta = basis_unigrid(london,mu)

100%|██████████| 14556/14556 [01:02<00:00, 234.73it/s]

In [141]:
W = np.linalg.pinv(theta)
W = np.dot(W,london['price'])
W.shape

(50,)

In [92]:
cov = np.cov(london['lat'],london['long'])

In [100]:
from numpy.linalg import inv

def multivariable_guassian(x,mu,cov):
    f = np.exp(-1/2*np.dot(np.dot((x- new_mu).T,inv(cov)),(x- new_mu)))
    return f

In [99]:
lat_mu,long_mu,_ = london.mean(0)
new_mu= np.array([lat_mu,long_mu])
new_mu=new_mu.reshape(2,1)


x=np.array([london['lat'][1],london['long'][1]]).reshape(2,1)
np.dot(np.dot((x- new_mu).T,inv(cov)),(x- new_mu))
#np.exp(-1/2*(x-new_mu).T*inv(cov)*(x-new_mu))

array([[0.47638404]])

In [117]:
london['lat'].values[1]
f= []

for i, j in zip(london['lat'].values,london['long'].values):
    x = np.array([i,j]) .reshape(2,1)
    a = multivariable_guassian(x,new_mu,cov)
    f.append(a)

In [143]:
def testRegressor(test_Input, param):
    mu = param[0]
    s = param[1]
    numBasisFncs = length(mu)+1
    Thetas = zeros(length(test_Input), numBasisFncs)
    for ii in tqdm(range(len(test_Input))):
        for jj in range(numBasisFncs):
            if jj == 0:
                Thetas[ii,jj] = 1
            else:
                Thetas[ii,jj] = np.exp( -( (((data['lat'][ii]-mu[jj-1,0])**2)/(2*(s[0]**2))) + \
                                       (((data['long'][ii]-mu[jj-1,1])**2)/(2*(s[1]**2))) ) )
    prediction = Thetas * param[2]
    return prediction